// Start loading angular 
angular.module(objParams.appName, ['pascalprecht.translate','ng-clamp'])
    .config(function ($translateProvider) {
        var locale = getLocale(objParams.constants.DEFAULT_LANGUAGE);
        objParams.constants.curLocale = locale;
        
        $translateProvider.translations('cs', {   "event_view_less" : "Zobrazit méně",   "event_where" : "Kde",   "event_this_month" : "Tento měsíc",   "event_no_upcoming_events_month" : "Žádné události tento měsíc",   "event_tooltip_all" : "Všechno",   "event_view_more" : "Zobrazit více",   "timezone" : "Časové pásmo",   "app_title" : "Google kalendář událostí",   "event_tooltip_copy_event" : "Kopírovat do mého kalendáře Google",   "event_description" : "Popis",   "event_no_upcoming_events_week" : "Žádné události tento týden",   "event_all_day" : "Celý den",   "event_no_title" : "bez názvu",   "test_event" : "Otestovat",   "event_when" : "Kdy",   "event_view_first" : "První",   "today" : "dnes",   "event_busy" : "zaneprázdněn" });
        $translateProvider.translations('da', {   "event_view_less" : "Se mindre",   "event_where" : "Hvor",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Ingen kommende begivenheder denne måned",   "event_tooltip_all" : "Alle",   "event_view_more" : "Se mere",   "timezone" : "Tidszone",   "app_title" : "Google Begivenhed Kalender",   "event_tooltip_copy_event" : "Kopier til min Google Kalender",   "event_description" : "Beskrivelse",   "event_no_upcoming_events_week" : "Ingen kommende begivenheder denne uge",   "event_all_day" : "Hele dagen",   "event_no_title" : "ingen titel",   "test_event" : "Test event",   "event_when" : "Hvornår",   "event_view_first" : "1st",   "today" : "i dag",   "event_busy" : "zajęty" });
        $translateProvider.translations('de', {   "event_view_less" : "Weniger anzeigen",   "event_where" : "Wo",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Es gibt diesen Monat keine bevorstehenden Veranstaltungen",   "event_tooltip_all" : "Alle",   "event_view_more" : "Mehr anzeigen",   "timezone" : "Zeitzone",   "app_title" : "Google Veranstaltungskalender",   "event_tooltip_copy_event" : "In meinen Google Kalender kopieren",   "event_description" : "Beschreibung",   "event_no_upcoming_events_week" : "Es gibt diese Woche keine bevorstehenden Veranstaltungen",   "event_all_day" : "Ganzer Tag",   "event_no_title" : "Kein Titel",   "test_event" : "Testveranstaltung",   "event_when" : "Wann",   "event_view_first" : "1st",   "today" : "Heute",   "event_busy" : "Nicht verfügbar" });
        $translateProvider.translations('en', {   "app_title": "Google Event Calendar",     "today" : "today",     "timezone" : "Timezone",     "event_tooltip_copy_event": "Copy to my Google Calendar",     "event_tooltip_all": "All",      "event_no_upcoming_events_month": "No events this month",     "event_no_upcoming_events_week": "No events this week",     "event_all_day": "All Day",     "event_description" : "Description",     "event_when" : "When",     "event_where" : "Where",     "event_no_title" :"no title",     "event_busy" : "busy",     "event_view_more" : "View More",     "event_view_less" : "View Less",    "event_view_first" : "1st",     "event_this_month" : "This month",      "test_event":"Test Event" });
        $translateProvider.translations('es', {   "event_view_less" : "Ver Menos",   "event_where" : "Dónde",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "No hay eventos durante este mes ",   "event_tooltip_all" : "Todo",   "event_view_more" : "Ver Más",   "timezone" : "Zona horaria",   "app_title" : "Google Event Calendar",   "event_tooltip_copy_event" : "Copiar a mi Google Calendar",   "event_description" : "Descripción",   "event_no_upcoming_events_week" : "No hay eventos durante esta semana",   "event_all_day" : "Todo el Día",   "event_no_title" : "sin título",   "test_event" : "Probar evento",   "event_when" : "Cuándo",   "event_view_first" : "1st",   "today" : "hoy",   "event_busy" : "ocupado" });
        $translateProvider.translations('fi', {   "event_view_less" : "View Less",   "event_where" : "Where",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "There are no upcoming events this month",   "event_tooltip_all" : "All",   "event_view_more" : "View More",   "timezone" : "Timezone",   "app_title" : "Google Event Calendar",   "event_tooltip_copy_event" : "Copy to my Google Calendar",   "event_description" : "Description",   "event_no_upcoming_events_week" : "There are no upcoming events this week",   "event_all_day" : "All Day",   "event_no_title" : "no title",   "test_event" : "Test Event",   "event_when" : "When",   "event_view_first" : "1st",   "today" : "today",   "event_busy" : "busy" });
        $translateProvider.translations('fr', {   "event_view_less" : "En voir moins",   "event_where" : "Où",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Il n'y a aucun événement ce mois-ci",   "event_tooltip_all" : "Tous",   "event_view_more" : "En voir plus",   "timezone" : "Fuseau Horaire ",   "app_title" : "Calendrier Événement Google",   "event_tooltip_copy_event" : "Copier sur mon Google Calendar",   "event_description" : "Description",   "event_no_upcoming_events_week" : "Il n'y a aucun événement cette semaine",   "event_all_day" : "Toute la journée",   "event_no_title" : "aucun titre",   "test_event" : "Événement test",   "event_when" : "Quand",   "event_view_first" : "1st",   "today" : "aujourd'hui",   "event_busy" : "occupé" });
        $translateProvider.translations('hi', {   "event_view_less" : "कम दिखाएं",   "event_where" : "कहां",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "इस माह कोई भी आगामी ईवेंट नहीं हैं",   "event_tooltip_all" : "सभी",   "event_view_more" : "अधिक देखें",   "timezone" : "समय-क्षेत्र",   "app_title" : "Google इवेंट कैलेंडर",   "event_tooltip_copy_event" : "मेरे Google कैलेंडर में कॉपी करें",   "event_description" : "वर्णन",   "event_no_upcoming_events_week" : "इस सप्ताह कोई भी आगामी ईवेंट नहीं हैं",   "event_all_day" : "सभी दिन",   "event_no_title" : "कोई शीर्षक नहीं",   "test_event" : "Test Event",   "event_when" : "कब",   "event_view_first" : "1st",   "today" : "आज",   "event_busy" : "व्यस्त" });
        $translateProvider.translations('it', {   "event_view_less" : "Vedi meno",   "event_where" : "Dove",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Non ci sono eventi questo mese",   "event_tooltip_all" : "Tutto",   "event_view_more" : "Vedi più",   "timezone" : "Fuso orario",   "app_title" : "Google Event Calendar",   "event_tooltip_copy_event" : "Copia sul mio Google Calendar",   "event_description" : "Descrizione",   "event_no_upcoming_events_week" : "Non ci sono eventi questa settimana",   "event_all_day" : "Tutto il giorno",   "event_no_title" : "senza titolo",   "test_event" : "Test Event",   "event_when" : "Quando",   "event_view_first" : "1st",   "today" : "oggi",   "event_busy" : "occupato" });
        $translateProvider.translations('ja', {   "event_view_less" : "折りたたむ",   "event_where" : "場所",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "この月の予定はありません",   "event_tooltip_all" : "全て",   "event_view_more" : "もっと見る",   "timezone" : "タイムゾーン",   "app_title" : "Google イベントカレンダー",   "event_tooltip_copy_event" : "Google カレンダーにコピーする",   "event_description" : "説明",   "event_no_upcoming_events_week" : "この週の予定はありません",   "event_all_day" : "終日",   "event_no_title" : "タイトル未定",   "test_event" : "イベントのサンプル",   "event_when" : "日時",   "event_view_first" : "1st",   "today" : "今日",   "event_busy" : "予定あり" });
        $translateProvider.translations('ko', {   "event_view_less" : "접기",   "event_where" : "장소",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "이번달에는 예정된 이벤트가 없습니다.",   "event_tooltip_all" : "전체",   "event_view_more" : "더 보기",   "timezone" : "시간대",   "app_title" : "Google 이벤트 캘린더",   "event_tooltip_copy_event" : "내 Google 캘린더로 복사",   "event_description" : "설명",   "event_no_upcoming_events_week" : "이번주는 예정된 이벤트가 없습니다.",   "event_all_day" : "종일",   "event_no_title" : "제목 없음",   "test_event" : "테스트",   "event_when" : "시간",   "event_view_first" : "1st",   "today" : "오늘",   "event_busy" : "바쁨" });
        $translateProvider.translations('nl', {   "event_view_less" : "Minder bekijken",   "event_where" : "Plaats",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Er zijn deze maand geen afspraken gepland",   "event_tooltip_all" : "Alle",   "event_view_more" : "Meer bekijken",   "timezone" : "Tijdzone",   "app_title" : "Google Agenda",   "event_tooltip_copy_event" : "Kopieer naar mijn Google-agenda",   "event_description" : "Beschrijving",   "event_no_upcoming_events_week" : "Er zijn deze week geen afspraken gepland",   "event_all_day" : "De hele dag",   "event_no_title" : "geen titel",   "test_event" : "Testevenement",   "event_when" : "Wanneer",   "event_view_first" : "1st",   "today" : "vandaag",   "event_busy" : "bezet" });
        $translateProvider.translations('no', {   "event_view_less" : "Vis mindre",   "event_where" : "Hvor",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Du har ingen kommende hendelser denne måneden",   "event_tooltip_all" : "Alle",   "event_view_more" : "Vis mer",   "timezone" : "Tidssone",   "app_title" : "Google hendelseskalender",   "event_tooltip_copy_event" : "Kopier til Google-kalenderen min",   "event_description" : "Beskrivelse",   "event_no_upcoming_events_week" : "Du har ingen kommende hendelser denne uken",   "event_all_day" : "Hele dagen",   "event_no_title" : "uten tittel",   "test_event" : "Test event",   "event_when" : "Når",   "event_view_first" : "1st",   "today" : "i dag",   "event_busy" : "opptatt" });
        $translateProvider.translations('pl', {   "event_view_less" : "Pokaż Mniej",   "event_where" : "Gdzie",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Brak eventów w tym miesiącu",   "event_tooltip_all" : "Wszystkie",   "event_view_more" : "Pokaż Więcej",   "timezone" : "Strefa Czasowa",   "app_title" : "Kalendarz Wydarzeń Google",   "event_tooltip_copy_event" : "Kopiuj do mojego Kalendarza Google",   "event_description" : "Opis",   "event_no_upcoming_events_week" : "Brak wydarzeń w tym tygodniu",   "event_all_day" : "Cały Dzień",   "event_no_title" : "brak tytułu",   "test_event" : "Przetestuj Wydarzenie",   "event_when" : "Kiedy",   "event_view_first" : "1st",   "today" : "dziś",   "event_busy" : "zajęty" });
        $translateProvider.translations('pt', {   "event_view_less" : "Ver Menos",   "event_where" : "Onde",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Não há eventos marcados para este mês",   "event_tooltip_all" : "Todos",   "event_view_more" : "Ver Mais",   "timezone" : "Fuso Horário",   "app_title" : "Agenda Google de Eventos",   "event_tooltip_copy_event" : "Copiar para meu Google Agenda",   "event_description" : "Descrição",   "event_no_upcoming_events_week" : "Não há eventos marcados essa semana",   "event_all_day" : "Todo Dia",   "event_no_title" : "sem título",   "test_event" : "Evento teste",   "event_when" : "Quando",   "event_view_first" : "1st",   "today" : "hoje",   "event_busy" : "ocupado" });
        $translateProvider.translations('ru', {   "event_view_less" : "Меньше",   "event_where" : "Где",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "В этом месяце нет предстоящих событий.",   "event_tooltip_all" : "Все",   "event_view_more" : "Больше",   "timezone" : "Часовой пояс ",   "app_title" : "Календарь Google",   "event_tooltip_copy_event" : "Скопировать в мой календарь Google.",   "event_description" : "Описание",   "event_no_upcoming_events_week" : "На этой неделе нет предстоящих событий.",   "event_all_day" : "Весь день",   "event_no_title" : "без заголовка",   "test_event" : "Ваше событие",   "event_when" : "Когда",   "event_view_first" : "1st",   "today" : "сегодня",   "event_busy" : "Время занято" });
        $translateProvider.translations('sv', {   "event_view_less" : "Visa mindre",   "event_where" : "Var",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Det finns inga kommande händelser denna månad",   "event_tooltip_all" : "Alla",   "event_view_more" : "Visa mer",   "timezone" : "Tidszon",   "app_title" : "Google Händelsekalender",   "event_tooltip_copy_event" : "Kopiera till Google Kalender",   "event_description" : "Beskrivning",   "event_no_upcoming_events_week" : "Det finns inga kommande händelser denna vecka",   "event_all_day" : "Hela dagen",   "event_no_title" : "ingen rubrik",   "test_event" : "Test event",   "event_when" : "När",   "event_view_first" : "1st",   "today" : "idag",   "event_busy" : "upptagen" });
        $translateProvider.translations('th', {   "event_view_less" : "View Less",   "event_where" : "Where",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "No events this month",   "event_tooltip_all" : "All",   "event_view_more" : "View More",   "timezone" : "Timezone",   "app_title" : "Google Event Calendar",   "event_tooltip_copy_event" : "Copy to my Google Calendar",   "event_description" : "Description",   "event_no_upcoming_events_week" : "No events this week",   "event_all_day" : "All Day",   "event_no_title" : "no title",   "test_event" : "Test Event",   "event_when" : "When",   "event_view_first" : "1st",   "today" : "today",   "event_busy" : "busy" });
        $translateProvider.translations('tr', {   "event_view_less" : "Daha Az",   "event_where" : "Nerede",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "Bu ay başka etkinlik bulunmuyor",   "event_tooltip_all" : "Hepsi",   "event_view_more" : "Daha Fazla",   "timezone" : "Saat dilimi",   "app_title" : "Google Etkinlik Takvimi",   "event_tooltip_copy_event" : "Google Takvimime Kopyala",   "event_description" : "Açıklama",   "event_no_upcoming_events_week" : "Bu hafta başka etkinlik bulunmuyor",   "event_all_day" : "Tam Gün",   "event_no_title" : "başlık yok",   "test_event" : "Test Etkinlik",   "event_when" : "Ne zaman",   "event_view_first" : "1st",   "today" : "bugün",   "event_busy" : "meşgul" });
        $translateProvider.translations('zh', {   "event_view_less" : "查看更少",   "event_where" : "地点",   "event_this_month" : "This month",   "event_no_upcoming_events_month" : "本月没有即将开展的活动",   "event_tooltip_all" : "全部",   "event_view_more" : "查看更多",   "timezone" : "时区",   "app_title" : "Google 活动日历",   "event_tooltip_copy_event" : "复制到我的 Google 日历",   "event_description" : "描述",   "event_no_upcoming_events_week" : "本周没有即将开展的活动",   "event_all_day" : "整天",   "event_no_title" : "无标题",   "test_event" : "Test Event",   "event_when" : "时间",   "event_view_first" : "1st",   "today" : "今天",   "event_busy" : "忙碌" });
        
        $translateProvider.preferredLanguage(locale)
        .fallbackLanguage(objParams.constants.DEFAULT_LANGUAGE)  // if translation file not exist then load English by default
        .useSanitizeValueStrategy(null); //http://angular-translate.github.io/docs/#/guide/19_security
})

.constant('OBJECT_PARAMS',objParams)

.run(function($log,$timeout) { //Start running the app 
    wixHandlers(); // remove record from db if app is deleted
});